# Generated by Django 4.2.28 on 2026-02-19 15:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
                ('kosten', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('klassenstufe_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('klassenstufe_max', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('kapazitaet', models.PositiveIntegerField()),
                ('termine', models.JSONField(default=list, help_text='Liste von Terminen mit Datum, Start- und Endzeit')),
                ('ort', models.CharField(blank=True, help_text='Ort der AG, z.B. Turnhalle, Klassenzimmer 101', max_length=200)),
                ('mitzubringen', models.TextField(blank=True, help_text='Was müssen die Kinder mitbringen? (z.B. Sportzeug, Mäppchen)')),
                ('hinweise', models.TextField(blank=True, help_text='Fragen / Organisatorische Hinweise')),
                ('verantwortlicher_name', models.CharField(max_length=200)),
                ('verantwortlicher_email', models.EmailField(max_length=254)),
                ('verantwortlicher_telefon', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Eingereicht'), ('APPROVED', 'Genehmigt')], default='SUBMITTED', max_length=20)),
            ],
            options={
                'verbose_name': 'AG',
                'verbose_name_plural': 'AGs',
            },
        ),
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmeldung_offen', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Konfiguration',
                'verbose_name_plural': 'Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='ArchivEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schueler_name', models.CharField(max_length=200)),
                ('schueler_email', models.EmailField(max_length=254)),
                ('ag_name', models.CharField(max_length=200)),
                ('halbyahr', models.CharField(help_text='z.B. 2023/24_H1', max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archiv-Eintrag',
                'verbose_name_plural': 'Archiv-Einträge',
                'ordering': ['-datum', 'schueler_name'],
            },
        ),
        migrations.CreateModel(
            name='SchuelerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Name des Kindes')),
                ('klassenstufe', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('notfall_telefon', models.CharField(default='', max_length=50, verbose_name='Notfall-Telefonnummer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schueler_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schüler',
                'verbose_name_plural': 'Schüler',
            },
        ),
        migrations.CreateModel(
            name='Anmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prio', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Wartend'), ('ACCEPTED', 'Zugelassen'), ('REJECTED', 'Abgelehnt/Warteliste')], default='PENDING', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('ag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='ags.ag')),
                ('schueler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='ags.schuelerprofile')),
            ],
            options={
                'verbose_name': 'Anmeldung',
                'verbose_name_plural': 'Anmeldungen',
            },
        ),
    ]
