# Generated by Django 4.2.27 on 2026-01-29 19:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
                ('kosten', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('klassenstufe_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('klassenstufe_max', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('kapazitaet', models.PositiveIntegerField()),
                ('termine', models.TextField(help_text='Liste von Terminen, z.B. Montags 14:00 - 15:30')),
                ('verantwortlicher_name', models.CharField(max_length=200)),
                ('verantwortlicher_email', models.EmailField(max_length=254)),
                ('verantwortlicher_telefon', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Eingereicht'), ('APPROVED', 'Genehmigt')], default='SUBMITTED', max_length=20)),
            ],
            options={
                'verbose_name': 'AG',
                'verbose_name_plural': 'AGs',
            },
        ),
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmeldung_offen', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Konfiguration',
                'verbose_name_plural': 'Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='SchuelerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klassenstufe', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schueler_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prio', models.PositiveSmallIntegerField(default=1)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('ag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='ags.ag')),
                ('schueler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prio'],
                'unique_together': {('schueler', 'ag')},
            },
        ),
    ]
