# Generated by Django 4.2.27 on 2026-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anmeldung',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Wartend'), ('ACCEPTED', 'Zugelassen'), ('REJECTED', 'Abgelehnt/Warteliste')], default='PENDING', max_length=20),
        ),
    ]
