# Generated by Django 4.2.28 on 2026-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveintrag',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Alle Details zur Zuteilung (AG-Zeiten, Ort etc.)'),
        ),
        migrations.AddConstraint(
            model_name='schuelerprofile',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_child_per_parent'),
        ),
    ]
