# Generated by Django 6.0.2 on 2026-02-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags', '0002_archiveintrag_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='ag_registrierung_offen',
            field=models.BooleanField(default=True, verbose_name='AG-Registrierung offen'),
        ),
    ]
