# Generated by Django 4.2.27 on 2026-01-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags', '0003_alter_ag_klassenstufe_max_alter_ag_klassenstufe_min_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anmeldung',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='anmeldung',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schuelerprofile',
            name='notfall_telefon',
            field=models.CharField(default='', max_length=50, verbose_name='Notfall-Telefonnummer'),
        ),
    ]
