# Generated by Django 6.0.3 on 2026-03-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags', '0003_appconfig_ag_registrierung_offen'),
    ]

    operations = [
        migrations.AddField(
            model_name='schuelerprofile',
            name='acceptance_email_sent',
            field=models.BooleanField(default=False, verbose_name='Zuteilungsmail gesendet'),
        ),
        migrations.AddField(
            model_name='schuelerprofile',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False, verbose_name='Anmeldebestätigung gesendet'),
        ),
    ]
