# Generated by Django 6.0.3 on 2026-03-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags', '0004_schuelerprofile_acceptance_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ag',
            name='leader_email_sent',
            field=models.BooleanField(default=False, verbose_name='E-Mail an AG-Leitung gesendet'),
        ),
    ]
