# Generated by Django 4.2.27 on 2026-01-29 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ags', '0004_alter_anmeldung_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schuelerprofile',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name des Kindes'),
        ),
        migrations.AlterField(
            model_name='anmeldung',
            name='schueler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='ags.schuelerprofile'),
        ),
        migrations.AlterField(
            model_name='schuelerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schueler_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
