# Generated by Django 4.2.27 on 2026-02-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags', '0005_schuelerprofile_name_alter_anmeldung_schueler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schueler_name', models.CharField(max_length=200)),
                ('schueler_email', models.EmailField(max_length=254)),
                ('ag_name', models.CharField(max_length=200)),
                ('halbyahr', models.CharField(help_text='z.B. 2023/24_H1', max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archiv-Eintrag',
                'verbose_name_plural': 'Archiv-Einträge',
                'ordering': ['-datum', 'schueler_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='anmeldung',
            options={'verbose_name': 'Anmeldung', 'verbose_name_plural': 'Anmeldungen'},
        ),
        migrations.AlterModelOptions(
            name='schuelerprofile',
            options={'verbose_name': 'Schüler', 'verbose_name_plural': 'Schüler'},
        ),
    ]
