# Generated by Django 4.2.28 on 2026-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags', '0006_archiveintrag_alter_anmeldung_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ag',
            name='ort',
            field=models.CharField(blank=True, help_text='Ort der AG, z.B. Turnhalle, Klassenzimmer 101', max_length=200),
        ),
    ]
